import type { NextPage } from "next";
import Head from "next/head";

import { useGetAllAbandonedCartsQuery } from "../generated/graphql";

const Home: NextPage = () => {
  const [{ data, error, fetching }] = useGetAllAbandonedCartsQuery();

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Abandoned Checkouts</h1>
        {error && <div>{error.message}</div>}
        {!fetching &&
          !error &&
          data?.checkouts?.edges.map((checkout) => (
            <>
              <div key={checkout.node.id}>Id: {checkout.node.id}</div>
              <div>Created: {checkout.node.created}</div>
            </>
          ))}
      </main>
    </div>
  );
};

export default Home;
